# Project routing configuration file
# src: source path
# path? : routing path， default is the path of src
# isMenu? :  Whether it is a menu, default is true
# children:
# isolated: render the route without a menu

- name: 工程化
  icon: ControlOutlined
  children:
    - name: crash信息收集
      src: engineering/crash
    - name: 开发
      src: engineering/development
    - name: 打包
      src: engineering/packaging
    - name: 自动更新
      src: engineering/update

- name: 应用
  icon: FormOutlined
  children:
    - name: 协议-从网页端唤起Electron应用
      src: application/protocol
    - name: Dialog与文件选择
      src: application/dialog
    - name: 菜单
      src: application/menu
    - name: 系统托盘
      src: application/tray
    - name: 下载管理器
      src: application/file-manager

- name: 窗口管理
  icon: WindowsFilled
  children:
    - name: 创建和管理窗口
      src: browser/window-operate
    - name: 主窗口隐藏和恢复
      src: browser/awaken
    - name: 窗口的聚焦和失焦
      src: browser/focus-blur
    - name: 全屏、最大化、最小化、恢复
      src: browser/window-fullscreen
    - name: 窗口通信
      src: browser/communication
    - name: 窗口类型
      src: browser/window-type
    - name: 窗口事件
      src: browser/window-event

- name: 其他
  icon: ProfileOutlined
  children:
    - name: 安全性
      src: others/security

- isolated: true
  src: browser/demo/communication-part1/client
  path: demo/communication-part1/client
- isolated: true
  src: browser/demo/communication-part1/main
  path: demo/communication-part1/main
- isolated: true
  src: browser/demo/communication-part2/client
  path: demo/communication-part2/client
- isolated: true
  src: browser/demo/communication-part2/main
  path: demo/communication-part2/main
- isolated: true
  src: browser/demo/communication-part3/client
  path: demo/communication-part3/client
- isolated: true
  src: browser/demo/communication-part3/main
  path: demo/communication-part3/main


- isolated: true
  src: browser/demo/window-close
  path: browser/demo/window-close

- isolated: true
  src: browser/demo/demo-window-type
  path: demo/window-type

- isolated: true
  src: browser/demo/full-screen
  path: demo/full-screen

- isolated: true
  src: editor
  path: editor

- isolated: true
  src: download-manager
  path: download-manager/demo

- isolated: true
  src: start
  path: start

- isolated: true
  src: apidoc
  path: apidoc